export default function Home() {
  return (
    <div className="font-crimson-text text-2xl bg-primary-green-900">
      <h1>Create Next App</h1>
      <p>Generated by create next app</p>
    </div>
  );
}
